# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6171e84b9203ca9c4d90416598ae14da002e34dc7f7de480d29a186faa5f8a8e35e73471152a05fd57fe39fd3b6ff49ea43dd7bd1df60205051895f7deb70d2
  autotask_user: <%= ENV["AUTOTASK_USER"] %>
  autotask_password: <%= ENV["AUTOTASK_PASSWORD"] %>
  autotask_wsdl: <%= ENV["AUTOTASk_WSDL"] %>
  autotask_account_owner: <%= ENV["AUTOTASK_ACCOUNT_OWNER"] %>

test:
  secret_key_base: 566835dd54c79cb2148cce851d065a604de44e7de8b2acb606ce3212a72a7011eacfbbafcd53e6329dceee734872fa8cb5853a646201610a66c70e6477decbee
  autotask_user: <%= ENV["AUTOTASK_USER"] %>
  autotask_password: <%= ENV["AUTOTASK_PASSWORD"] %>
  autotask_wsdl: <%= ENV["AUTOTASk_WSDL"] %>
  autotask_account_owner: <%= ENV["AUTOTASK_ACCOUNT_OWNER"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  autotask_user: <%= ENV["AUTOTASK_USER"] %>
  autotask_password: <%= ENV["AUTOTASK_PASSWORD"] %>
  autotask_wsdl: <%= ENV["AUTOTASk_WSDL"] %>
  autotask_account_owner: <%= ENV["AUTOTASK_ACCOUNT_OWNER"] %>